### PR TITLE
Update to reflect Tictail API changes

### PR DESCRIPTION
**Pull request by jede**

### CODE REVIEW

**Comment by kalasjocke** [comment]
:heart:

**Comment by kalasjocke** [comment]
@javve @jede We should totally fix real endpoints for this, but I guess this goes for now.

**Comment by jede** [comment]
@kalasjocke Whats not to like?? :P But yeah, would be awesome with some kind of endpoint! :+1:

**Comment by kalasjocke** [comment]
@jede Or that we could build this project as an real Tictail app that you could install in your development store. A bit smoother journey than now. :smile:

**Comment by jede** [comment]
@kalasjocke Wow, nice! Didn't know you could do that!

**Comment by javve** [comment]
@kalasjocke Oh, interesting idea! :grin:

**Pull request merged**
